/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gusto.embedded_api.models.operations;

import static com.gusto.embedded_api.operations.Operations.RequestOperation;

import com.gusto.embedded_api.SDKConfiguration;
import com.gusto.embedded_api.operations.GetEvents;
import com.gusto.embedded_api.utils.Headers;
import com.gusto.embedded_api.utils.Utils;

public class GetEventsRequestBuilder {

    private GetEventsRequest request;
    private GetEventsSecurity security;
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers(); 

    public GetEventsRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public GetEventsRequestBuilder request(GetEventsRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public GetEventsRequestBuilder security(GetEventsSecurity security) {
        Utils.checkNotNull(security, "security");
        this.security = security;
        return this;
    }

    public GetEventsResponse call() {
        
        RequestOperation<GetEventsRequest, GetEventsResponse> operation
              = new GetEvents.Sync(sdkConfiguration, security, _headers);

        return operation.handleResponse(operation.doRequest(request));
    }
}
